swagger: '2.0'
info:
  title: Integration Request API
  description: API to perform create/update and (un)subscribe operations on data items
    https://marketlogic.atlassian.net/wiki/spaces/SI/pages/647824170/Data+Integration+Pipeline+-+Technical+Design
  version: '1.0.0'
host: integration-request.marketlogicsoftware.com
basePath: /
tags:
- name: item
  description: supports creating/updating, (un)linking with assets and tenants
- name: asset
  description: supports creating assets
paths:
  /providers/{provider_id}/items:
    post:
      tags:
      - item
      summary: creates an item
      operationId: postItem
      security:
      - oauth: [ cross-tenant ]
    get:
      tags:
      - item
      summary: get the item
      operationId: getItem
      security:
      - oauth: [ cross-tenant ]
  /providers/_find-by-item-id:
    get:
      tags:
      - provider
      summary: get provider for an item id
      operationId: getProviderForItemId
      security:
      - oauth: [ cross-tenant ]
  /assets:
    post:
      tags:
      - asset
      summary: creates an asset
      operationId: postAsset
      security:
      - oauth: [ cross-tenant ]
  /items/_reindex:
    post:
      tags:
      - item
      summary: re-index the items
      operationId: reIndex
      security:
      - oauth: [ cross-tenant ]
  /items:
    get:
      tags:
      - item
      summary: get items by passing list of ids
      operationId: getItemsByIDs
      security:
      - oauth: [ cross-tenant ]
  /items/_find-by-example:
    post:
      tags:
      - item
      summary: finds items by example, for the moment only exact match on top-level properties is supported
      operationId: findItems
      security:
      - oauth: [ cross-tenant ]
    # tenant operations
  /tenants/{tenant_id}/providers/{provider_id}:
    delete:
      tags:
        - tenant
      summary: unsubscribes and removes overwritten properties for specific tenant
      operationId: unsubscribeProvider
      security:
        - oauth: [ global-tenant ]
  /tenants/{tenant_id}/products/{product_id}:
    delete:
      tags:
        - tenant
      summary: unsubscribes and removes overwritten properties for specific tenant
      operationId: unsubscribeProduct
      security:
        - oauth: [ global-tenant ]
  /tenants/{tenant_id}/assets/{asset_id}:
    delete:
      tags:
        - tenant
      summary: unsubscribes and removes overwritten properties for specific tenant
      operationId: unsubscribeAsset
      security:
        - oauth: [ global-tenant ]
  /tenants/{tenant_id}/items/{item_id}:
    delete:
      tags:
        - tenant
      summary: unsubscribes and removes overwritten properties for specific tenant
      operationId: unsubscribeItem
      security:
        - oauth: [ global-tenant ]
securityDefinitions:
  oauth:
    type: oauth2
    flow: application
    tokenUrl: http://token-business-service:8080/token
    scopes:
      cross-tenant: Grants access for cross-tenant operations
